name: build and push docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    # ➕ Étape 1 : Connexion à DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ 'elouafi010203@gmail.com' }}
        password: ${{ 'Bienvenue_' }}

    # ➕ Étape 2 : Construction de l’image Docker
    - name: Build Docker image
      run: docker build -t ${{ 'elouafi010203@gmail.com' }}/mydotnetapp:latest .

    # ➕ Étape 3 : Push de l’image vers DockerHub
    - name: Push Docker image
      run: docker push ${{ 'elouafi010203@gmail.com' }}/mydotnetapp:latest
